#!/usr/bin/env python3
"""The one command to run after a fresh CQL test run.

Runs, in order:
  1. compare_results.main()             -- scores actual vs expected, writes
                                            output_results.csv, discrepancy_report.md,
                                            qicore_engine_diff.csv, catalog_issue_details.md,
                                            appends to run-history.jsonl
  2. generate_engine_issues_doc.main()  -- regenerates defect-tracking/engine-issues.md
                                            from known_issues.json
  3. check_generated.run_checks()       -- confirms both generated files agree with
                                            their source (should always pass right after
                                            step 1-2; failing here means a bug in this
                                            script, not the data)

Before this script existed, engine-issues.md had to be regenerated by hand
after editing known_issues.json, and it was routinely forgotten -- the two
forked for 11 commits before anyone noticed (see check_generated.py's
docstring). Running this instead of `compare_results.py` directly means the
md can no longer lag the catalog.

Usage:
  python3 scripts/run_reports.py
  python3 scripts/run_reports.py --known-issues path/to/known_issues.json

Run from the repo root; all default paths are relative to it, matching
scripts/compare_results.py's own defaults.
"""
import argparse
import os
import sys

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
_COMPARISON_DIR = os.path.join(_SCRIPTS_DIR, "comparison")
sys.path.insert(0, _SCRIPTS_DIR)
sys.path.insert(0, _COMPARISON_DIR)

import check_generated
import compare_results
import generate_engine_issues_doc

REPO_ROOT = os.path.dirname(_SCRIPTS_DIR)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--expected", default=os.path.join(_COMPARISON_DIR, "expected_results.csv"))
    parser.add_argument("--actual", default=os.path.join(_COMPARISON_DIR, "actual_results.csv"))
    parser.add_argument("--output", default=os.path.join(_COMPARISON_DIR, "output_results.csv"))
    parser.add_argument("--report", default=os.path.join(_COMPARISON_DIR, "discrepancy_report.md"))
    parser.add_argument("--known-issues", default=os.path.join(_COMPARISON_DIR, "known_issues.json"))
    parser.add_argument("--qicore-actual", default=os.path.join(_COMPARISON_DIR, "qicore-2025-actual-results.csv"))
    parser.add_argument("--qicore-diff-csv", default=os.path.join(_COMPARISON_DIR, "qicore_engine_diff.csv"))
    parser.add_argument("--engine-issues-output",
                        default=os.path.join(REPO_ROOT, "defect-tracking", "engine-issues.md"))
    parser.add_argument("--run-history-path", default=None,
                        help="Override run-history.jsonl location (default: "
                             "scripts/comparison/run-history.jsonl).")
    parser.add_argument("--skip-drift-check", action="store_true",
                        help="Skip the post-run check_generated verification.")
    args = parser.parse_args(argv)

    print("== 1/3: compare_results ==")
    compare_results.main(
        args.expected,
        args.actual,
        args.output,
        args.report,
        args.known_issues,
        args.qicore_actual,
        args.qicore_diff_csv,
        run_history_path=args.run_history_path,
    )

    print()
    print("== 2/3: regenerate engine-issues.md ==")
    generate_engine_issues_doc.main([args.known_issues, args.engine_issues_output])

    if args.skip_drift_check:
        return 0

    print()
    print("== 3/3: verify no drift ==")
    clean = check_generated.run_checks()
    if not clean:
        print()
        print("run_reports.py produced generated files that do not match "
             "regeneration from their own source -- this indicates a bug in "
             "run_reports.py or check_generated.py, not stale data (they "
             "were both just regenerated together). Please investigate.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
