#!/usr/bin/env python3
"""The one command to run after a fresh CQL test run.

Runs, in order:
  0. extract_population_actual.main()   -- turns input/tests/results/ into
                                            scripts/comparison/actual_results.csv
                                            (auto-detects txt vs JSON format).
                                            Skipped if --skip-extract, or if the
                                            results directory has no result files.
  1. build_catalog.main()               -- compiles defect-tracking/issues/ into
                                            known_issues.json (the file is now a
                                            build artifact, not hand-edited)
  2. compare_results.main()             -- scores actual vs expected, writes
                                            output_results.csv, discrepancy_report.md,
                                            qicore_engine_diff.csv, catalog_issue_details.md,
                                            appends to run-history.jsonl
  3. generate_improvement_tracking.main() -- regenerates
                                            defect-tracking/improvement-tracking.md
                                            from run-history.jsonl (which step 2 just
                                            appended one line to)
  4. generate_engine_issues_doc.main()  -- regenerates defect-tracking/engine-issues.md
                                            from known_issues.json
  5. check_generated.run_checks()       -- confirms all generated files agree with
                                            their source (should always pass right after
                                            step 0-4; failing here means a bug in this
                                            script, not the data)

Before this script existed, engine-issues.md had to be regenerated by hand
after editing known_issues.json, and it was routinely forgotten -- the two
forked for 11 commits before anyone noticed (see check_generated.py's
docstring). Running this instead of `compare_results.py` directly means the
md can no longer lag the catalog.

Before this update, the caller also had to remember to run
extract_population_actual.py first so that the freshly-written .txt traces
under input/tests/results/ made it into actual_results.csv. That step is now
the first thing this script does; --skip-extract preserves the old behavior
for callers that want to pass a pre-built --actual.

Usage:
  python3 scripts/run_reports.py
  python3 scripts/run_reports.py --skip-extract
  python3 scripts/run_reports.py --known-issues path/to/known_issues.json

Run from the repo root; all default paths are relative to it, matching
scripts/compare_results.py's own defaults.
"""
import argparse
import glob
import os
import sys

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
_COMPARISON_DIR = os.path.join(_SCRIPTS_DIR, "comparison")
sys.path.insert(0, _SCRIPTS_DIR)
sys.path.insert(0, _COMPARISON_DIR)

import check_generated
import build_catalog
import compare_results
import extract_population_actual
import generate_engine_issues_doc
import generate_improvement_tracking

REPO_ROOT = os.path.dirname(_SCRIPTS_DIR)

_DEFAULT_RESULTS_DIR = "./input/tests/results"


def _has_result_files(results_dir: str) -> bool:
    """True when the results directory contains anything worth extracting.

    A coarse presence check used by step 0: if no ``*.txt`` trace or
    ``TestCaseResult-*.json`` exists, we leave ``--actual`` untouched rather
    than overwriting it with an empty CSV. Matches ``load_measure_sections``
    and ``load_json_results`` semantics -- *.txt traces may live directly in
    the dir or inside per-measure subdirectories.
    """
    if not os.path.isdir(results_dir):
        return False
    if glob.glob(os.path.join(results_dir, "**", "*.txt"), recursive=True):
        return True
    if glob.glob(os.path.join(results_dir, "**", "TestCaseResult-*.json"), recursive=True):
        return True
    return False


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--expected", default=os.path.join(_COMPARISON_DIR, "expected_results.csv"))
    parser.add_argument("--actual", default=os.path.join(_COMPARISON_DIR, "actual_results.csv"))
    parser.add_argument("--output", default=os.path.join(_COMPARISON_DIR, "output_results.csv"))
    parser.add_argument("--report", default=os.path.join(_COMPARISON_DIR, "discrepancy_report.md"))
    parser.add_argument("--known-issues", default=os.path.join(_COMPARISON_DIR, "known_issues.json"))
    parser.add_argument("--issues-dir",
                        default=os.path.join(REPO_ROOT, "defect-tracking", "issues"),
                        help="Authored catalog source compiled by step 1.")
    parser.add_argument("--skip-catalog-build", action="store_true",
                        help="Skip step 1; use known_issues.json as-is (hand-edited).")
    parser.add_argument("--qicore-actual", default=os.path.join(_COMPARISON_DIR, "qicore-2025-actual-results.csv"))
    parser.add_argument("--qicore-diff-csv", default=os.path.join(_COMPARISON_DIR, "qicore_engine_diff.csv"))
    parser.add_argument("--engine-issues-output",
                        default=os.path.join(REPO_ROOT, "defect-tracking", "engine-issues.md"))
    parser.add_argument("--improvement-tracking-output",
                        default=os.path.join(REPO_ROOT, "defect-tracking", "improvement-tracking.md"))
    parser.add_argument("--run-history-path", default=None,
                        help="Override run-history.jsonl location (default: "
                             "scripts/comparison/run-history.jsonl).")
    parser.add_argument("--results-dir", default=_DEFAULT_RESULTS_DIR,
                        help=f"Directory holding the CQL engine output. Defaults "
                             f"to '{_DEFAULT_RESULTS_DIR}'; auto-detects *.txt vs "
                             f"TestCaseResult-*.json.")
    parser.add_argument("--skip-extract", action="store_true",
                        help="Skip step 0; use --actual as-is. Use when the "
                             "actual_results.csv is already up to date or when "
                             "you are running tests against a fixture CSV.")
    parser.add_argument("--skip-drift-check", action="store_true",
                        help="Skip the post-run check_generated verification.")
    args = parser.parse_args(argv)

    if not args.skip_extract:
        if _has_result_files(args.results_dir):
            print("== 0/6: extract actual_results.csv from CQL engine output ==")
            extract_population_actual.main([
                "--results-dir", args.results_dir,
                "--output", args.actual,
            ])
            print()
        else:
            print(f"== 0/6: no result files in {args.results_dir}; "
                  f"skipping extraction and using {args.actual} as-is ==")
            print()

    if not args.skip_catalog_build:
        print("== 1/6: compile known_issues.json from issue files ==")
        build_catalog.main(["-d", args.issues_dir, "-o", args.known_issues])
        print()

    print("== 2/6: compare_results ==")
    compare_results.main(
        args.expected,
        args.actual,
        args.output,
        args.report,
        args.known_issues,
        args.qicore_actual,
        args.qicore_diff_csv,
        run_history_path=args.run_history_path,
    )

    print()
    print("== 3/6: regenerate improvement-tracking.md ==")
    generate_improvement_tracking.main(
        [args.run_history_path or "", args.improvement_tracking_output])

    print()
    print("== 4/6: regenerate engine-issues.md ==")
    generate_engine_issues_doc.main([args.known_issues, args.engine_issues_output])

    if args.skip_drift_check:
        return 0

    print()
    print("== 5/6: verify no drift ==")
    clean = check_generated.run_checks()
    if not clean:
        print()
        print("run_reports.py produced generated files that do not match "
             "regeneration from their own source -- this indicates a bug in "
             "run_reports.py or check_generated.py, not stale data (they "
             "were both just regenerated together). Please investigate.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
